export enum ROLES {
  ADMIN = 'ADMIN',
  COMPANY = 'COMPANY',
  FARMER = 'FARMER',
  COWBOY = 'COWBOY',
}

export enum LISTS {
  COLOR = 'COLOR',
  STATE = 'STATE',
  STAGE = 'STAGE',
  LOT = 'LOT',
  MEDICINE = 'MEDICINE',
  WEIGHT = 'WEIGHT',
  BREED = 'BREED',
  REPRODUCTION = 'REPRODUCTION',
  GENDER = 'GENDER',
  LOSS = 'LOSS',
  VACCINE = 'VACCINE',
}
